services:
  app:
    image: ${IMAGE_URI}
    container_name: qroad-be
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_PRESIGN_EXP_MINUTES: ${AWS_S3_PRESIGN_EXP_MINUTES}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_AUTOCONFIGURE_EXCLUDE: ${SPRING_AUTOCONFIGURE_EXCLUDE}
      LOG_DIR: /log
    volumes:
      - /home/ubuntu/log/qroad-be:/log
