# SQL 바인딩 파라미터 로그
logging.level.org.hibernate.type.descriptor.sql=TRACE 


# ==========================
# Swagger 설정
# ==========================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
